language: go

os:
  - linux
  - osx

go:
  - 1.11.x
  - 1.12.x
  - master

env:
  - GOMAXPROCS=4
  - GO111MODULE=on
  - GO15VENDOREXPERIMENT=1

gobuild_args: -x -ldflags "-extldflags -static"
sudo: false

before_install:
  - go get -v golang.org/x/lint/golint

branches:
  only:
    - master

notifications:
  email: false

script:
    - make test test-race
    - make build
    - ./genpasswd
